function [ legendhandle ] = legendtitle( legendhandle, textstring )
%Add text on top of the legend

hlt = text(...
    'Parent', legendhandle.DecorationContainer, ...
    'String', textstring, ...
    'HorizontalAlignment', 'Center', ...
    'VerticalAlignment', 'bottom', ...
    'Position', [0.5, 1.05, 0], ...
    'Units', 'normalized');
legendhandle.Interpreter = 'Latex';
legend boxoff;
end

