% Description: Layout for the load tab.
%   - inputs: 
%           Envents coming from the GUI.
%   - outputs: 
%           User interface (UI) control values for the load tab control functions.
% Date of creation: 2017-07-11
% Author: Benjamin Bolling
% Modification date:
% Modifier:

%% [FUNCTIONNAME] function.

function [ h_figure, UI ] = load( h_figure, pos, h_tabs, tab_load)
% Folders choise button
UI.LoadFolderButton = uicontrol('Parent', tab_load, ...
'Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.02 0.94 0.47 0.05], ...
'Enable', 'on', ...
'String', 'Choose filefolder', ...
'TooltipString', 'Press to choose which filefolder to use');

% Load file button
UI.LoadFileButton = uicontrol('Parent', tab_load, ...
'Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.02 0.4 0.47 0.05], ...
'Enable', 'off', ...
'String', 'Load file', ...
'TooltipString', 'Press to load the file(s) from the list above.');

% Unload file button
UI.UnLoadFileButton = uicontrol('Parent', tab_load, ...
'Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.51 0.4 0.47 0.05], ...
'Enable', 'off', ...
'String', 'Unload file', ...
'TooltipString', 'Press to unload the selected file(s) from the list below.');

% Filtetype information for writing in the filetype selection box
UI.FiletypeSelectionBoxInformationText = uicontrol('Parent', tab_load, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.91 0.47 0.033],...
'fontsize', 12,...
'String','Filetype:');

% only a . in a textbox
UI.FiletypeSelectionBoxTheDot = uicontrol('Parent', tab_load, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.872 0.02 0.04],...
'fontsize', 24,...
'String','.');

% Filetype selection box
UI.FiletypeEditBox = uicontrol('Parent', tab_load, ...
'style','edit',...
'units','normalized',...
'position',[0.05 0.87 0.44 0.037],...
'string',{'mat'},...                 
'fontweight','bold',...
'horizontalalign','center',...
'Enable', 'on',...
'fontsize',14);

% Fileslist information - files in folder:
UI.FilesInFolderInformation = uicontrol('Parent', tab_load, ...
'Style','text',...
'units','normalized',...
'Position',[0.02 0.74 0.47 0.04],...
'FontSize', 14, ...
'String','Files in folder:');

% Fileslist information - files loaded:
UI.FilesInFolderInformation = uicontrol('Parent', tab_load, ...
'Style','text',...
'units','normalized',...
'Position',[0.51 0.74 0.47 0.04],...
'FontSize', 14, ...
'String','Files loaded:');

% Selected file information:
UI.SelectedFileInformation = uicontrol('Parent', tab_load, ...
'Style','listbox',...
'units','normalized',...
'Position',[0.02 0.05 0.96 0.2],...
'HorizontalAlignment', 'left',...
'FontSize', 14, ...
'Enable', 'on', ...
'String','Last loaded file information.');

% Shows all the files with selected file extension that exists in chosen
% folder
UI.ListOfFilesInFolder = uicontrol('Parent', tab_load, ...
'Style', 'listbox', ...
'Units', 'normalized', ...
'Position', [0.02 0.45 0.47 0.3], ...
'FontSize', 14, ...
'Enable', 'on', ...
'String', {''}, ...
'TooltipString', 'Select file');

% Shows all the file which are loaded and will be plotted
UI.LoadedFiles = uicontrol('Parent', tab_load, ...
'Style', 'listbox', ...
'Units', 'normalized', ...
'Position', [0.51 0.45 0.47 0.3],...
'FontSize', 14, ...
'Enable', 'on', ...
'String', {''}, ...
'Max',0,'Min',0,...
'TooltipString', 'Select file');

UI.md_default_radiobuttongroup = uibuttongroup('Parent', tab_load,...
'Units', 'normalized', ...
'Position', [0.5 0.865 0.47 0.12]);

%First radio button defined will be selected.
UI.md_default_radiobutton_local = uicontrol('Parent', UI.md_default_radiobuttongroup, ...
'Style', 'radiobutton', ...
'Units', 'normalized', ...
'Position', [0 0.6 1 0.3],...
'FontSize', 12, ...
'String', 'Local metadata',...
'TooltipString', 'Local metadata used');

UI.md_default_radiobutton_system = uicontrol('Parent', UI.md_default_radiobuttongroup, ...
'Style', 'radiobutton', ...
'Units', 'normalized', ...
'Position', [0 0.3 1 0.3],...
'FontSize', 12, ...
'String', 'System metadata',...
'TooltipString', 'The local metadata have to be located in the same folder as the files being loaded and have the name. If not, the system metadata will be used');

UI.md_default_radiobutton_combined = uicontrol('Parent', UI.md_default_radiobuttongroup, ...
'Style', 'radiobutton', ...
'Units', 'normalized', ...
'Position', [0 0 1 0.3],...
'FontSize', 12, ...
'String', 'Combined metadata',...
'TooltipString', 'Combined will read the system metadata, followed by the local metadata');
end
