% Description: Layout for the plot tab.
%   - inputs: 
%           Main graphical objects, incl. main figure of the GUI.
%   - outputs: 
%           User interface (UI) graphical objects for the plot tab.
% Date of creation: 2017-01-04
% Author: Benjamin Bolling
% Modification date:
% Modifier:

function [ h_figure, UIctrl_plot ] = plot( h_figure, pos, h_tabs, tab_plot)
%% Functions
% Information about the listbox below
UIctrl_plot.h_plot_tabs = uitabgroup(tab_plot,'Position',[0 0 1 0.64]);
% Def plot tab:
UIctrl_plot.tab_plot_def = uitab(UIctrl_plot.h_plot_tabs,'Title','Pre-defined plots');
% New plot tab:
UIctrl_plot.tab_plot_new = uitab(UIctrl_plot.h_plot_tabs,'Title','New plot conf');
% New signal tab:
UIctrl_plot.tab_signal_new = uitab(UIctrl_plot.h_plot_tabs,'Title','New signal conf');
%% Defined Plotting
[h_figure, UIctrl_plot.def]         = GUI.create_layout.plot.def_plot(h_figure, pos, UIctrl_plot.h_plot_tabs, UIctrl_plot.tab_plot_def);
%% New Plotting:
[h_figure, UIctrl_plot.new]         = GUI.create_layout.plot.new_plot(h_figure, pos, UIctrl_plot.h_plot_tabs, UIctrl_plot.tab_plot_new);
%% New Signal:
[h_figure, UIctrl_plot.new_signal]  = GUI.create_layout.plot.new_signal(h_figure, pos, UIctrl_plot.h_plot_tabs, UIctrl_plot.tab_signal_new);

% A textbox
UIctrl_plot.InformationText_Filter_Selection = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'FontSize', 14, ...
'Position',[0.02 0.65 0.37 0.06],...
'HorizontalAlignment', 'right', ...
'String','Select external filter:');

% Popup for filter selection
UIctrl_plot.Popup_Filter_Selection = uicontrol('Parent', tab_plot, ...
'Style','popupmenu',...
'Enable', 'off', ...
'Units', 'normalized',...
'FontSize', 14, ...
'Position',[0.41 0.65 0.57 0.06],...
'String', {'filter'});

% A textbox
UIctrl_plot.InformationText_LoadedFilesPlotting = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.96 0.96 0.03],...
'FontSize', 12, ...
'String','Select experiment(s) to plot:');

% Shows all the files which are loaded into memory
UIctrl_plot.LoadedFilesPlotting = uicontrol('Parent', tab_plot, ...
'Style', 'listbox', ...
'Units', 'normalized', ...
'Position', [0.02 0.72 0.96 0.24], ...
'FontSize', 14, ...
'Enable', 'on', ...
'String', {''}, ...
'Max',2,'Min',0,...
'TooltipString', 'Select file');

end