% Description: Layout for the plot tab.
%   - inputs: 
%           Envents coming from the GUI.
%   - outputs: 
%           User interface (UI) control values for the plot tab control functions.
% Date of creation: 2017-07-11
% Author: Benjamin Bolling
% Modification date:
% Modifier:

function [ h_figure, UIctrl_plot ] = plot( h_figure, pos, h_tabs, tab_plot)
%% Functions
% Information about the listbox below
UI.h_plot_tabs = uitabgroup(tab_plot,'Position',[0 0 1 0.7]);
% Def plot tab:
tab_plot_def = uitab(UI.h_plot_tabs,'Title','Defined plot configurations');
% New lot tab:
tab_plot_new = uitab(UI.h_plot_tabs,'Title','New plot configuration');
%% Defined Plotting
[h_figure, UIctrl_plot.def] = GUI.create_layout.plot.def_plot(h_figure, pos, UI.h_plot_tabs, tab_plot_def);
%% New Plotting:
[h_figure, UIctrl_plot.new] = GUI.create_layout.plot.new_plot(h_figure, pos, UI.h_plot_tabs, tab_plot_new);

% Shows all the file which are loaded and will be plotted
UIctrl_plot.InformationText_LoadedFilesPlotting = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.96 0.96 0.03],...
'FontSize', 12, ...
'String','Select experiment(s) to plot:');
UIctrl_plot.LoadedFilesPlotting = uicontrol('Parent', tab_plot, ...
'Style', 'listbox', ...
'Units', 'normalized', ...
'Position', [0.02 0.71 0.96 0.25], ...
'FontSize', 14, ...
'Enable', 'on', ...
'String', {''}, ...
'Max',2,'Min',0,...
'TooltipString', 'Select file');

end