% Description: Creates a dialog to gather input needed for the new filter.
%   - inputs:
%           Tree node -> filter 'path'          (base_path)
%   - outputs:
%           Modified loaded file metadata.      (mdata_n)
% Date of creation: 2017-08-18.
% Author: Benjamin Bolling.
% Modification date:
% Modifier:
function [ ] = Add_Filter_Choice()
md_GUI = evalin('base', 'md_GUI');
%function choice = choosedialog
screensize = md_GUI.UI.screensize;

d = dialog('Position',[screensize(3)/3 screensize(4)/3 screensize(3)/3 screensize(4)/2],'Name','Select One');
txt_name = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.02 0.9 0.28 0.05],...
       'String','New filter name: ');
txt_exp = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.02 0.75 0.28 0.05],...
       'String','Select experiment: ');
txt_type = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.02 0.6 0.28 0.05],...
       'String','Filter values type: ');
txt_value = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.02 0.45 0.28 0.05],...
       'String','Value: ');
txt_translate = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.02 0.3 0.28 0.05],...
       'String','Translate condition: ');
txt_invert = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.02 0.15 0.28 0.05],...
       'String','Invert filter: ');

popup_exp = uicontrol('Parent',d,...
       'Style','popup',...
       'units', 'normalized',...
       'fontsize', 12,...
       'Position',[0.35 0.75 0.55 0.05],...
       'String',{'Red';'Green';'Blue'},...
       'Callback',@popup_callback);
popup_type = uicontrol('Parent',d,...
       'Style','popup',...
       'units', 'normalized',...
       'fontsize', 12,...
       'Position',[0.35 0.75 0.55 0.05],...
       'String',{'Red';'Green';'Blue'},...
       'Callback',@popup_callback);
popup_translate = uicontrol('Parent',d,...
       'Style','popup',...
       'units', 'normalized',...
       'fontsize', 12,...
       'Position',[0.35 0.75 0.55 0.05],...
       'String',{'Red';'Green';'Blue'},...
       'Callback',@popup_callback);
popup_invert = uicontrol('Parent',d,...
       'Style','popup',...
       'units', 'normalized',...
       'fontsize', 12,...
       'Position',[0.35 0.75 0.55 0.05],...
       'String',{'On''},...
       'Callback',@popup_callback);
   
btn = uicontrol('Parent',d,...
       'Position',[89 20 70 25],...
       'String','Close',...
       'Callback','delete(gcf)');

choice = 'Red';

% Wait for d to close before running to completion
uiwait(d);

   function popup_callback(popup,event)
      idx = popup.Value;
      popup_items = popup.String;
      % This code uses dot notation to get properties.
      % Dot notation runs in R2014b and later.
      % For R2014a and earlier:
      % idx = get(popup,'Value');
      % popup_items = get(popup,'String');
      choice = char(popup_items(idx,:));
   end

end