% Description: Creates a dialog to gather input needed for the new filter.
%   - inputs:
%           Tree node -> filter 'path'          (base_path)
%   - outputs:
%           Modified loaded file metadata.      (mdata_n)
% Date of creation: 2017-08-18.
% Author: Benjamin Bolling.
% Modification date:
% Modifier:
%function [ ] = Edit_Filter_Choice()
function [ operator, valsel ] = Edit_Operator(operator, valsel)
md_GUI = evalin('base', 'md_GUI');
%function choice = choosedialog
screensize = md_GUI.UI.screensize;
operators = {'AND', 'OR'};
for lx = 1:length(operators)
    if strcmp(char(operators(lx)), operator)
        operator_val = lx;
    end
end
d = dialog('Position',[screensize(3)/4 screensize(4)/5 screensize(3)/3 screensize(4)/15],'Name','Edit operators');
txt_operator = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.05 0.05 0.28 0.9],...
       'String','Choose operator type: ');
popup_operator = uicontrol('Parent',d,...
       'Style','popup',...
       'units', 'normalized',...
       'fontsize', 14,...
       'Position',[0.35 0.05 0.45 0.9],...
       'String',operators,...
       'Value', operator_val,...
       'Callback',@popup_operator_callback);
OK_btn = uicontrol('Parent',d,...
       'Style','pushbutton',...
       'units', 'normalized',...
       'fontsize', 12,...
       'Position',[0.85 0.05 0.1 0.9],...
       'String','Ok',...
       'Callback',@Ok_btn_callback);
    function popup_operator_callback(hObject,event)
        idx = popup_operator.Value;
        popup_items = popup_operator.String;
        operator = char(popup_items(idx,:));
    end
    function Ok_btn_callback(hObject, eventdata)
        valsel = 1;
        delete(gcf)
    end
% Wait for d to close before running to completion
uiwait(d);
end