% Description: Creates a dialog to gather input needed for the new filter.
%   - inputs:
%           Tree node -> filter 'path'          (base_path)
%   - outputs:
%           Modified loaded file metadata.      (mdata_n)
% Date of creation: 2017-08-18.
% Author: Benjamin Bolling.
% Modification date:
% Modifier:
%function [ ] = Edit_Filter_Choice()
function [ operator, valsel ] = Edit_Operator(operator, valsel)
md_GUI = evalin('base', 'md_GUI');
%function choice = choosedialog
screensize = md_GUI.UI.screensize;
d = dialog('Position',[screensize(3)/4 screensize(4)/5 screensize(3)/3 screensize(4)/2],'Name','Edit operators');
txt_operator = uicontrol('Parent',d,...
       'Style','text',...
       'units', 'normalized',...
       'fontsize', 12,...
       'HorizontalAlignment', 'right',...
       'Position',[0.02 0.85 0.28 0.1],...
       'String','Choose operator type: ');
operators = ['AND', 'OR'];
for lx = 1:length(operators)
    if strcmp(char(operators(lx)), operator)
        operator_val = lx;
    end
end
popup_operator = uicontrol('Parent',d,...
       'Style','popup',...
       'units', 'normalized',...
       'fontsize', 12,...
       'Position',[0.35 0.85 0.55 0.1],...
       'String',operators,...
       'Value', operator_val,...
       'Callback',@popup_operator_callback);
OK_btn = uicontrol('Parent',d,...
       'Style','pushbutton',...
       'units', 'normalized',...
       'fontsize', 12,...
       'Position',[0.85 0.03 0.1 0.06],...
       'String','Ok',...
       'Callback','delete(gcf)');
    function popup_operator_callback(popup_type,event)
        idx = popup_operator.Value;
        popup_items = popup_operator.String;
        operator = char(popup_items(idx,:));
        %% Message to log_box - cell_to_be_inserted:
        cell_to_be_inserted = ['New data pointer set: ', full_datapointer_string];
        [ md_GUI.UI.log_box_string ] = GUI.multitab.insertCell ( md_GUI.UI.log_box_string, cell_to_be_inserted );
        md_GUI.UI.UImultitab.log_box.String = md_GUI.UI.log_box_string;
        % End of new message to log_box function.
        base_value.data_pointer = full_datapointer_string;
    end
% Wait for d to close before running to completion
uiwait(d);
end