function jRangeSlider = rangeslider(hParent, Min, Max, LowValue, HighValue, Name, ....
    Position, MajorTickSpacing, MinorTickSpacing, StateChangedCallback)

% more direct instantiation
% jRS = com.jidesoft.swing.RangeSlider(0,100,20,70); %min,max,low,high
% [jRangeSlider{i}, hRangeSlider{i}] = javacomponent(jRS,[0,0,200,80],hF);%posx,posy,width,height
  jRS = com.jidesoft.swing.RangeSlider;
  [jRangeSlider, hRangeSlider] = javacomponent(jRS,[],hParent);
  % modify rangeslider position
  set(hRangeSlider,'Position', Position)
  % modify range slider properties
  set(jRangeSlider, ...
      'Minimum',Min,...
      'Maximum',Max,...
      'LowValue',LowValue,...
      'HighValue',HighValue,...
      'Name',Name,...
      'MajorTickSpacing',MajorTickSpacing,...
      'MinorTickSpacing',MinorTickSpacing, ...
      'PaintTicks',true,...
      'PaintLabels',true, ...
      'StateChangedCallback',StateChangedCallback);
end
