% Description: Layout for the plot tab.
%   - inputs: 
%           Envents coming from the GUI.
%   - outputs: 
%           User interface (UI) control values for the plot tab control functions.
% Date of creation: 2017-07-11
% Author: Benjamin Bolling
% Modification date:
% Modifier:


function [ h_figure, UI ] = def_plot( h_figure, pos, h_tabs, tab_plot)

% Information about popup menu for plot selection
UI.InformationText_plot_selection = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.85 0.26 0.1],...
'FontSize', 12, ...
'HorizontalAlignment', 'left', ...
'String','Pick a plot:');

UI.pre_def_plot_radiobuttongroup = uibuttongroup('Parent', tab_plot,...
'Units', 'normalized', ...
'Position', [0.28 0.88 0.7 0.1]);

%First radio button defined will be selected.
UI.pre_def_plot_radiobutton_built_in = uicontrol('Parent', UI.pre_def_plot_radiobuttongroup, ...
'Style', 'radiobutton', ...
'Units', 'normalized', ...
'Position', [0 0 0.5 1],...
'FontSize', 12, ...
'String', 'Built-in plots',...
'TooltipString', 'Plot configurations that was built-in (hard-coded for the acquisition device).');

UI.pre_def_plot_radiobutton_customized = uicontrol('Parent', UI.pre_def_plot_radiobuttongroup, ...
'Style', 'radiobutton', ...
'Units', 'normalized', ...
'Position', [0.5 0 0.5 1],...
'FontSize', 12, ...
'String', 'Customized plots',...
'TooltipString', 'Plot configurations that was constructed or customized by user.');


% Popup box with plot type def in:
% md_GUI.mdata_n.exp1.plot.det1.KER_sum
% Gets def when loading exp and by sel exp in plot loadedfiles listbox.
UI.Popup_plot_type = uicontrol('Parent', tab_plot, ...
'Enable', 'off', ...
'Style','popupmenu',...
'String', {''},...
'Units', 'normalized',...
'FontSize', 12, ...
'Position',[0.02 0.82 0.96 0.05]);

% Plot the way selected from popup above
UI.PlotButton = uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Units', 'normalized',...
'FontSize', 16, ...
'Position',[0.2 0.54 0.6 0.2],...
'Enable', 'off', ...
'String', 'Plot', ...
'TooltipString', 'Press to plot');
% Plot function used:
%macro.plot.create.plot(md_GUI.data_n.exp1, md_GUI.mdata_n.exp1.plot.det1.KER_sum)

% Plot the way selected from popup above
UI.ModPlotBkgButton = uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Units', 'normalized',...
'FontSize', 12, ...
'Position',[0.001 0.01 0.998 0.25],...
'Enable', 'off', ...
'String', '');

UI.InformationText_mod_plot = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.26 0.9 0.05],...
'FontSize', 14, ...
'HorizontalAlignment', 'left', ...
'String','Modify plots');

% Give a link to edit the plot configuration:
UI.PlotConfDuplButton = uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Units', 'normalized',...
'FontSize', 12, ...
'Position',[0.02 0.15 0.45 0.09],...
'Enable', 'off', ...
'String', 'Duplicate', ...
'TooltipString', 'Duplicate the plot configuration of the selected plot: histogram, figure, axes, Graphical object and condition configuration.');

% Give a link to edit the plot configuration:
UI.PlotConfEditButton = uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Units', 'normalized',...
'FontSize', 12, ...
'Position',[0.53 0.15 0.45 0.09],...
'Enable', 'off', ...
'String', 'Edit', ...
'TooltipString', 'Modify the plot configuration of the selected plot: histogram, figure, axes, Graphical object and condition configuration.');

% Give a link to edit the plot configuration:
UI.PlotConfRmvButton = uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Units', 'normalized',...
'FontSize', 12, ...
'Position',[0.53 0.04 0.45 0.09],...
'Enable', 'off', ...
'String', 'Remove', ...
'TooltipString', 'Remove the selected plot configuragion from the selected experiment(s).');
end