% Description: Layout for the plot tab.
%   - inputs: 
%           Envents coming from the GUI.
%   - outputs: 
%           User interface (UI) control values for the plot tab control functions.
% Date of creation: 2017-07-11
% Author: Benjamin Bolling
% Modification date:
% Modifier:

function [ h_figure, UI ] = new_signal( h_figure, pos, h_tabs, tab_plot)
%% Functions
% Information about the listbox below

UI.BackgroundBox =uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Enable', 'off', ...
'Units', 'normalized',...
'FontSize', 14, ...
'BackgroundColor', [0.935 0.935 0.935], ...
'Position',[0.005 0.01 0.99 0.98],...
'Enable', 'off', ...
'String', '', ...
'TooltipString', '');

%% Functions for radioboxes
UI.signals_radiobuttongroup = uibuttongroup('Parent', tab_plot,...
'Units', 'normalized', ...
'Position', [0.1 0.88 0.8 0.1]);

%First radio button defined will be selected.
UI.signals_radiobutton_built_in = uicontrol('Parent', UI.signals_radiobuttongroup, ...
'Style', 'radiobutton', ...
'Units', 'normalized', ...
'Position', [0 0 0.5 1],...
'FontSize', 12, ...
'String', 'Built-in signals',...
'TooltipString', 'Signals configurations that was built-in (hard-coded for the acquisition device).');

UI.signals_radiobutton_customized = uicontrol('Parent', UI.signals_radiobuttongroup, ...
'Style', 'radiobutton', ...
'Units', 'normalized', ...
'Position', [0.5 0 0.5 1],...
'FontSize', 12, ...
'String', 'Customized signals',...
'TooltipString', 'Signal configurations that was constructed or customized by user.');

% List of signal pointers
UI.signals_list = uicontrol('Parent', tab_plot, ...
'Style','list',...
'Units', 'normalized',...
'Position',[0.02 0.05 0.47 0.8],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','-');

% Duplicate signal
UI.duplicate_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.51 0.75 0.47 0.1],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','Duplicate');

% New signal
UI.new_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.51 0.63 0.47 0.1],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','New...');

% Edit existing signal (customized or defined by user)
UI.edit_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.51 0.51 0.47 0.1],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','Edit...');

% Remove existing signal (customized or defined by user)
UI.remove_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.51 0.39 0.47 0.1],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','Remove...');

end