% Description: Layout for the plot tab.
%   - inputs: 
%           Envents coming from the GUI.
%   - outputs: 
%           User interface (UI) control values for the plot tab control functions.
% Date of creation: 2017-07-11
% Author: Benjamin Bolling
% Modification date:
% Modifier:

function [ h_figure, UI ] = new_plot( h_figure, pos, h_tabs, tab_plot)
%% Functions
% Information about the listbox below

UI.BackgroundBox =uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Enable', 'off', ...
'Units', 'normalized',...
'FontSize', 14, ...
'BackgroundColor', [0.935 0.935 0.935], ...
'Position',[0.005 0.12 0.99 0.88],...
'Enable', 'off', ...
'String', '', ...
'TooltipString', '');

% Information text about Signal settings
UI.SignalSettings_Text = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.91 0.96 0.06],...
'FontSize', 14, ...
'HorizontalAlignment', 'left', ...
'String','Signal settings');

% Information text about x-signal
UI.x_text = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.02 0.84 0.47 0.06],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'String','X (Ordinate)');

% Information text about y-signal
UI.y_text = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'Position',[0.51 0.84 0.47 0.06],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'String','Y (Abscissa)');


% Enable y-signals pointers list
UI.y_signals_checkbox = uicontrol('Parent', tab_plot, ...
'Style','checkbox',...
'Units', 'normalized',...
'Position',[0.51 0.77 0.47 0.06],...
'FontSize', 14, ...
'HorizontalAlignment', 'right', ...
'Enable', 'off',...
'String','Specify abscissa');

% List of x-signals pointers
UI.x_signals_list = uicontrol('Parent', tab_plot, ...
'Style','list',...
'Units', 'normalized',...
'Position',[0.02 0.41 0.47 0.42],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','-');

% List of y-signals pointers
UI.y_signals_list = uicontrol('Parent', tab_plot, ...
'Style','list',...
'Units', 'normalized',...
'Position',[0.51 0.41 0.47 0.35],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','-');

% Add new x-signal pointer
UI.new_x_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.02 0.32 0.47 0.08],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','New...');

% Add new y-signal pointer
UI.new_y_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.51 0.32 0.47 0.08],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','New...');

% Add new x-signal pointer
UI.edit_x_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.02 0.23 0.47 0.08],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','Edit...');

% Add new y-signal pointer
UI.edit_y_signal = uicontrol('Parent', tab_plot, ...
'Style','pushbutton',...
'Units', 'normalized',...
'Position',[0.51 0.23 0.47 0.08],...
'FontSize', 14, ...
'HorizontalAlignment', 'center', ...
'Enable', 'off',...
'String','Edit...');

% Information about popup menu for how to plot signals selected
UI.PopupPlotSelected_Text = uicontrol('Parent', tab_plot, ...
'Style','text',...
'Units', 'normalized',...
'FontSize', 14, ...
'Position',[0.02 0.13 0.47 0.06],...
'HorizontalAlignment', 'right', ...
'String','Destination:');

% Selecting how to plot it
UI.PopupPlotSelected = uicontrol('Parent', tab_plot, ...
'Style','popupmenu',...
'Enable', 'off', ...
'Units', 'normalized',...
'FontSize', 14, ...
'Position',[0.51 0.13 0.47 0.08],...
'String',{'Plot all in new figure together', 'Plot all separately', 'Plot selection into pre-existing figure'});

% Plot the new selected stuff from the popups
UI.PlotButton = uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Units', 'normalized',...
'FontSize', 14, ...
'Position',[0.52 0.01 0.47 0.1],...
'Enable', 'off', ...
'String', 'Plot', ...
'TooltipString', 'Press to plot');

% Plot the new selected stuff from the popups
UI.PlotConfButton = uicontrol('Parent', tab_plot, ...
'Style', 'pushbutton', ...
'Units', 'normalized',...
'FontSize', 14, ...
'Position',[0.02 0.01 0.47 0.1],...
'Enable', 'off', ...
'String', 'Plot Configurations', ...
'TooltipString', 'Press to configure plot settings for all selected experiments for the selected plot type');
end